# =============================================================================
# Synthetic data: realistic forestry with thinnings + compressed rotation
# =============================================================================
#
# Truth generated by Yasso07-intact.
#
# Timeline (110 years):
#
#   ROTATION 1 (normal, 50 yr cycle):
#     1-5:     Stable mature forest
#     6:       Clearcut 1
#     7-55:    Recovery (with thinnings at yr 16 and 26)
#       16:    Thinning 1 (10yr post-CC1)
#       26:    Thinning 2 (20yr post-CC1)
#     
#   ROTATION 2 (compressed 30%, 35 yr cycle):
#     56:      Clearcut 2
#     57-90:   Recovery (with thinnings at yr 63 and 70)
#       63:    Thinning 3 (7yr post-CC2 ≈ 10×0.7)
#       70:    Thinning 4 (14yr post-CC2 ≈ 20×0.7)
#     91:      Clearcut 3
#     92-110:  Recovery (no thinning yet)
#
# Observations: every 2 years, yr 0 to yr 56 (CC2)
# Prediction: yr 56-110
# =============================================================================

library(Matrix)
source("yasso07_intact.R")

set.seed(42)

# -----------------------------------------------------------------
# 1. Parameters
# -----------------------------------------------------------------
PA = c(
  -0.5172509, -3.551512, -0.3458914, -0.2660175,
  0.044852223, 0.0029265443, 0.9779027, 0.6373951,
  0.3124745,   0.018712098,  0.022490378, 0.011738963,
  0.00099046889, 0.3361765, 0.041966144, 0.089885026,
  0.089501545, -0.0022709155,
  0.17, -0.0015, 0.17, -0.0015, 0.17, -0.0015, 0.0,
  -2.935411,
  0.0,
  101.8253, 260.0,
  -0.080983594, -0.315179, -0.5173524, 0.0, 0.0,
  -0.00024180325,
  0.0015341907,
  101.8253, 260.0,
  -0.5391662, 1.18574, -0.2632936,
  0.0, 0.0, 0.0
)

FRAG_RATE = log(2) / 6   # half-life 6 yr

# -----------------------------------------------------------------
# 2. Climate
# -----------------------------------------------------------------
n_total = 110

MAT = 4.5 + 0.012 * (1:n_total) + rnorm(n_total, 0, 0.6)
TA  = rep(13.5, n_total) + rnorm(n_total, 0, 0.4)
PR  = rep(580, n_total) + rnorm(n_total, 0, 50)
PR  = pmax(PR, 350)

climate = data.frame(
  year = 1:n_total,
  MAT  = round(MAT, 2),
  TA   = round(TA, 2),
  PR   = round(PR, 0)
)

# -----------------------------------------------------------------
# 3. AWEN fractions and diameters
# -----------------------------------------------------------------
awen_nw = c(0.48, 0.17, 0.05, 0.30)
awen_fw = c(0.10, 0.12, 0.03, 0.75)
awen_cw = c(0.05, 0.10, 0.02, 0.83)
awen_st = c(0.03, 0.08, 0.02, 0.87)

d_nw = 0
d_fw = 2
d_cw = 15
d_st = 35

# Equilibrium rates [Mg C/ha/yr] for mature forest
rate_nw_eq = 2.0
rate_fw_eq = 0.8
rate_cw_eq = 0.5
rate_st_eq = 0.1

# -----------------------------------------------------------------
# 4. Disturbance event definitions
# -----------------------------------------------------------------
# Clearcut pulse [Mg C/ha] — absolute values for the event year
cc_nw = rate_nw_eq * 1.5
cc_fw = rate_fw_eq * 4.0
cc_cw = rate_cw_eq * 3.0
cc_st = 5.0

# Thinning pulse — smaller, removes ~30% of standing volume
# Added ON TOP of background recovery inputs
thin_nw = 0.5    # some extra needle fall
thin_fw = 1.5    # branches from removed trees
thin_cw = 0.8    # tops
thin_st = 1.0    # a few stumps (smaller than CC stumps)

# -----------------------------------------------------------------
# 5. Build input time series
# -----------------------------------------------------------------
rate_nw = numeric(n_total)
rate_fw = numeric(n_total)
rate_cw = numeric(n_total)
rate_st = numeric(n_total)

tau = 10
residual = 0.05

# Recovery function: fraction of equilibrium input at time t after disturbance
recovery_frac = function(t) {
  residual + (1 - residual) * (1 - exp(-t / tau))
}

# Thinning dip: inputs drop ~20% for 2 years then recover
# (canopy opens, less litterfall temporarily, but not as dramatic as CC)
thin_dip = 0.80

# Helper: fill with noise
noisy = function(val, sd) pmax(val + rnorm(1, 0, sd), 0)

# --- Build year by year ---
for (y in 1:n_total) {
  
  # ============================================================
  # ROTATION 1: CC1 at yr 6, thinnings at 16, 26, CC2 at 56
  # ============================================================
  
  if (y <= 5) {
    # Stable mature forest
    rate_nw[y] = noisy(rate_nw_eq, 0.10)
    rate_fw[y] = noisy(rate_fw_eq, 0.05)
    rate_cw[y] = noisy(rate_cw_eq, 0.04)
    rate_st[y] = noisy(rate_st_eq, 0.02)
    
  } else if (y == 6) {
    # CC1
    rate_nw[y] = cc_nw
    rate_fw[y] = cc_fw
    rate_cw[y] = cc_cw
    rate_st[y] = cc_st
    
  } else if (y >= 7 & y <= 55) {
    # Recovery from CC1
    t_since = y - 6
    frac = recovery_frac(t_since)
    
    rate_nw[y] = noisy(rate_nw_eq * frac, 0.05)
    rate_fw[y] = noisy(rate_fw_eq * frac, 0.03)
    rate_cw[y] = noisy(rate_cw_eq * frac, 0.02)
    rate_st[y] = noisy(rate_st_eq * frac, 0.005)
    
    # Thinning 1 at year 16: pulse on top + slight dip next year
    if (y == 16) {
      rate_nw[y] = rate_nw[y] + thin_nw
      rate_fw[y] = rate_fw[y] + thin_fw
      rate_cw[y] = rate_cw[y] + thin_cw
      rate_st[y] = rate_st[y] + thin_st
    }
    if (y == 17) {
      rate_nw[y] = rate_nw[y] * thin_dip
      rate_fw[y] = rate_fw[y] * thin_dip
    }
    
    # Thinning 2 at year 26
    if (y == 26) {
      rate_nw[y] = rate_nw[y] + thin_nw
      rate_fw[y] = rate_fw[y] + thin_fw
      rate_cw[y] = rate_cw[y] + thin_cw
      rate_st[y] = rate_st[y] + thin_st
    }
    if (y == 27) {
      rate_nw[y] = rate_nw[y] * thin_dip
      rate_fw[y] = rate_fw[y] * thin_dip
    }
    
    # ============================================================
    # ROTATION 2: CC2 at yr 56, thinnings at 63, 70, CC3 at 91
    # (compressed 30%: 35yr cycle, thinnings at 7 and 14yr)
    # ============================================================
    
  } else if (y == 56) {
    # CC2
    rate_nw[y] = cc_nw
    rate_fw[y] = cc_fw
    rate_cw[y] = cc_cw
    rate_st[y] = cc_st
    
  } else if (y >= 57 & y <= 90) {
    # Recovery from CC2
    t_since = y - 56
    frac = recovery_frac(t_since)
    
    rate_nw[y] = noisy(rate_nw_eq * frac, 0.05)
    rate_fw[y] = noisy(rate_fw_eq * frac, 0.03)
    rate_cw[y] = noisy(rate_cw_eq * frac, 0.02)
    rate_st[y] = noisy(rate_st_eq * frac, 0.005)
    
    # Thinning 3 at year 63 (7yr post-CC2)
    if (y == 63) {
      rate_nw[y] = rate_nw[y] + thin_nw
      rate_fw[y] = rate_fw[y] + thin_fw
      rate_cw[y] = rate_cw[y] + thin_cw
      rate_st[y] = rate_st[y] + thin_st
    }
    if (y == 64) {
      rate_nw[y] = rate_nw[y] * thin_dip
      rate_fw[y] = rate_fw[y] * thin_dip
    }
    
    # Thinning 4 at year 70 (14yr post-CC2)
    if (y == 70) {
      rate_nw[y] = rate_nw[y] + thin_nw
      rate_fw[y] = rate_fw[y] + thin_fw
      rate_cw[y] = rate_cw[y] + thin_cw
      rate_st[y] = rate_st[y] + thin_st
    }
    if (y == 71) {
      rate_nw[y] = rate_nw[y] * thin_dip
      rate_fw[y] = rate_fw[y] * thin_dip
    }
    
  } else if (y == 91) {
    # CC3
    rate_nw[y] = cc_nw
    rate_fw[y] = cc_fw
    rate_cw[y] = cc_cw
    rate_st[y] = cc_st
    
  } else if (y >= 92) {
    # Recovery from CC3
    t_since = y - 91
    frac = recovery_frac(t_since)
    
    rate_nw[y] = noisy(rate_nw_eq * frac, 0.05)
    rate_fw[y] = noisy(rate_fw_eq * frac, 0.03)
    rate_cw[y] = noisy(rate_cw_eq * frac, 0.02)
    rate_st[y] = noisy(rate_st_eq * frac, 0.005)
  }
}

# Ensure no negatives
rate_nw = pmax(rate_nw, 0)
rate_fw = pmax(rate_fw, 0)
rate_cw = pmax(rate_cw, 0)
rate_st = pmax(rate_st, 0)

# AWENH matrices
litter_nw = outer(rate_nw, c(awen_nw, 0))
litter_fw = outer(rate_fw, c(awen_fw, 0))
litter_cw = outer(rate_cw, c(awen_cw, 0))
litter_st = outer(rate_st, c(awen_st, 0))
litter_total = litter_nw + litter_fw + litter_cw + litter_st

litter_df = data.frame(
  year    = 1:n_total,
  A       = round(litter_total[, 1], 4),
  W       = round(litter_total[, 2], 4),
  E       = round(litter_total[, 3], 4),
  N       = round(litter_total[, 4], 4),
  H       = round(litter_total[, 5], 4),
  total   = round(rowSums(litter_total), 4),
  rate_nw = round(rate_nw, 4),
  rate_fw = round(rate_fw, 4),
  rate_cw = round(rate_cw, 4),
  rate_st = round(rate_st, 4)
)

# -----------------------------------------------------------------
# 6. Spinup
# -----------------------------------------------------------------
mean_MAT = mean(climate$MAT)
mean_TA  = mean(climate$TA)
mean_PR  = mean(climate$PR)

n_state = 6

p_nw = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                 rep(0, n_state), c(rate_nw_eq * awen_nw, 0),
                                 d_nw, PA, 3000, UseIntactPool = TRUE, FragRate = FRAG_RATE))

p_fw = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                 rep(0, n_state), c(rate_fw_eq * awen_fw, 0),
                                 d_fw, PA, 3000, UseIntactPool = TRUE, FragRate = FRAG_RATE))

p_cw = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                 rep(0, n_state), c(rate_cw_eq * awen_cw, 0),
                                 d_cw, PA, 3000, UseIntactPool = TRUE, FragRate = FRAG_RATE))

p_st = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                 rep(0, n_state), c(rate_st_eq * awen_st, 0),
                                 d_st, PA, 3000, UseIntactPool = TRUE, FragRate = FRAG_RATE))

cat("Spinup SOC:", round(sum(p_nw) + sum(p_fw) + sum(p_cw) + sum(p_st), 2), "Mg C/ha\n")

# -----------------------------------------------------------------
# 7. Generate "true" SOC with intact pool model
# -----------------------------------------------------------------
soc_true = numeric(n_total + 1)
soc_true[1] = sum(p_nw) + sum(p_fw) + sum(p_cw) + sum(p_st)

for (y in 1:n_total) {
  p_nw = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                   p_nw, litter_nw[y, ], d_nw, PA, 1, UseIntactPool = TRUE, FragRate = FRAG_RATE))
  p_fw = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                   p_fw, litter_fw[y, ], d_fw, PA, 1, UseIntactPool = TRUE, FragRate = FRAG_RATE))
  p_cw = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                   p_cw, litter_cw[y, ], d_cw, PA, 1, UseIntactPool = TRUE, FragRate = FRAG_RATE))
  p_st = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                   p_st, litter_st[y, ], d_st, PA, 1, UseIntactPool = TRUE, FragRate = FRAG_RATE))
  
  soc_true[y + 1] = sum(p_nw) + sum(p_fw) + sum(p_cw) + sum(p_st)
}

# -----------------------------------------------------------------
# 8. Observations: every 2 years, yr 0 to CC2 (yr 56)
# -----------------------------------------------------------------
cc2_year = 56
obs_years = seq(0, cc2_year, by = 2)
obs_cv = 0.05

observations = data.frame(
  year       = obs_years,
  SOC_true   = round(soc_true[obs_years + 1], 2),
  SOC_obs    = round(soc_true[obs_years + 1] * (1 + rnorm(length(obs_years), 0, obs_cv)), 2),
  SOC_obs_sd = round(soc_true[obs_years + 1] * obs_cv, 2)
)

# -----------------------------------------------------------------
# 9. Standard Yasso07 reference (same params, uncalibrated)
# -----------------------------------------------------------------
p_nw_s = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                   rep(0, 5), c(rate_nw_eq * awen_nw, 0), d_nw, PA, 3000, UseIntactPool = FALSE))
p_fw_s = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                   rep(0, 5), c(rate_fw_eq * awen_fw, 0), d_fw, PA, 3000, UseIntactPool = FALSE))
p_cw_s = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                   rep(0, 5), c(rate_cw_eq * awen_cw, 0), d_cw, PA, 3000, UseIntactPool = FALSE))
p_st_s = as.numeric(yasso07.intact(mean_MAT, mean_TA, mean_PR,
                                   rep(0, 5), c(rate_st_eq * awen_st, 0), d_st, PA, 3000, UseIntactPool = FALSE))

soc_std_ref = numeric(n_total + 1)
soc_std_ref[1] = sum(p_nw_s) + sum(p_fw_s) + sum(p_cw_s) + sum(p_st_s)

for (y in 1:n_total) {
  p_nw_s = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                     p_nw_s, litter_nw[y, ], d_nw, PA, 1, UseIntactPool = FALSE))
  p_fw_s = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                     p_fw_s, litter_fw[y, ], d_fw, PA, 1, UseIntactPool = FALSE))
  p_cw_s = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                     p_cw_s, litter_cw[y, ], d_cw, PA, 1, UseIntactPool = FALSE))
  p_st_s = as.numeric(yasso07.intact(climate$MAT[y], climate$TA[y], climate$PR[y],
                                     p_st_s, litter_st[y, ], d_st, PA, 1, UseIntactPool = FALSE))
  soc_std_ref[y + 1] = sum(p_nw_s) + sum(p_fw_s) + sum(p_cw_s) + sum(p_st_s)
}

# -----------------------------------------------------------------
# 10. Save
# -----------------------------------------------------------------
synthetic_data = list(
  climate        = climate,
  litter_total   = litter_df,
  litter_nw      = litter_nw,
  litter_fw      = litter_fw,
  litter_cw      = litter_cw,
  litter_st      = litter_st,
  awen_fractions = list(nonwoody = awen_nw, fine_woody = awen_fw,
                        coarse_woody = awen_cw, stumps = awen_st),
  diameters      = c(nonwoody = d_nw, fine_woody = d_fw,
                     coarse_woody = d_cw, stumps = d_st),
  parameters     = PA,
  frag_rate      = FRAG_RATE,
  soc_true_intact   = data.frame(year = 0:n_total, total = round(soc_true, 4)),
  soc_true_standard = data.frame(year = 0:n_total, total = round(soc_std_ref, 4)),
  observations   = observations,
  scenario       = list(
    n_total      = n_total,
    cc1_year     = 6,
    thin1_year   = 16,
    thin2_year   = 26,
    cc2_year     = 56,
    thin3_year   = 63,
    thin4_year   = 70,
    cc3_year     = 91,
    obs_end      = cc2_year,
    recovery_tau = tau
  )
)

saveRDS(synthetic_data, "yasso07_synthetic_data.rds")

# -----------------------------------------------------------------
# 11. Summary
# -----------------------------------------------------------------
cat("\n=== Dataset summary ===\n")
cat("Total years:", n_total, "\n")
cat("Rotation 1 (normal): CC1=6, Thin=16,26, CC2=56 (50yr)\n")
cat("Rotation 2 (compressed): CC2=56, Thin=63,70, CC3=91 (35yr)\n")
cat("Recovery after CC3: yr 92-110\n")
cat("Observations:", nrow(observations), "points (yr 0 to", cc2_year, ")\n")
cat("FragRate:", round(FRAG_RATE, 4), "(half-life", round(log(2)/FRAG_RATE, 1), "yr)\n\n")
cat("SOC yr 0:  ", round(soc_true[1], 1), "\n")
cat("SOC yr 6:  ", round(soc_true[7], 1), "(post-CC1)\n")
cat("SOC yr 56: ", round(soc_true[57], 1), "(post-CC2)\n")
cat("SOC yr 91: ", round(soc_true[92], 1), "(post-CC3)\n")
cat("SOC yr 110:", round(soc_true[111], 1), "\n")