setwd("/Users/ilmenichetti/Library/CloudStorage/OneDrive-Valtion/HIKET/SOC_modeling")
# T1 -- per-model results-at-a-glance table (the performance values that F4's redesign
# dropped, plus the structural + auxiliary-sigma + forecast columns that carry the story).
# Ties together: complexity (pools/free params) | skill (R2 calib/holdout, RMSE) |
# inputs (effective litter flux sigma_input x J-bar) | init (sigma_init) | forecast (2084).
# Writes a LaTeX booktabs-free tabular fragment for \input, and prints the numbers.

rid <- list(SP1="20260710_104903", TP2="20260710_104904", TP3="20260710_104904",
            Yasso07="20260710_104902", Yasso15="20260710_104902", Yasso20="20260710_102431")
pools <- c(SP1=1, TP2=2, TP3=3, Yasso07=5, Yasso15=5, Yasso20=5)   # AWENH = 5 for Yasso
JBAR  <- 2.472                                                     # shared mean litter (flux_pair)
runs  <- "Calibration_real_data_transient/runs"

cache <- readRDS("manuscript/figures/F4_cache.rds")               # for the 2084 forecast
row <- function(m) {
  b  <- readRDS(sprintf("%s/%s_posterior_predictive_%s.rds", runs, m, rid[[m]]))
  po <- readRDS(sprintf("%s/%s_posterior_%s.rds", runs, m, rid[[m]]))
  si <- median(po[, "sigma_input"]); sc <- median(po[, "sigma_init"])
  s2084 <- cache$stored[[m]]$m[cache$stored[[m]]$year == 2084]
  data.frame(model = m, pools = pools[[m]], free = ncol(po),
             R2c = b$metrics_calib$R2, R2h = b$metrics_holdout$R2,
             RMSE = b$metrics_holdout$RMSE_mean,
             effJ = si * JBAR, sinit = sc, soc2084 = s2084)
}
T <- do.call(rbind, lapply(names(rid), row))
print(T, row.names = FALSE, digits = 3)

# --- LaTeX tabular fragment ---
esc <- function(x) x
f <- "manuscript/figures/T1_model_summary.tex"
con <- file(f, "w")
wl <- function(...) cat(..., "\n", sep = "", file = con)
wl("% auto-generated by build_T1_model_summary.R -- per-model summary")
wl("\\begin{tabular}{lccccccc}")
wl("\\hline")
wl("Model & Pools & Free & $R^2$ & $R^2$ & RMSE & Eff.\\ flux & $\\sigma_{\\mathrm{init}}$ \\\\")
wl(" & & params & (cal) & (hold) & (hold) & $\\sigma_{\\mathrm{inp}}\\bar J$ & \\\\")
wl("\\hline")
for (i in seq_len(nrow(T))) with(T[i, ],
  wl(sprintf("%s & %d & %d & %.3f & %.3f & %.0f & %.1f & %.2f \\\\",
             model, pools, free, R2c, R2h, RMSE, effJ, sinit)))
wl("\\hline")
wl("\\end{tabular}")
close(con)
cat("\nwrote", f, "\n")
cat("(Eff. flux = median sigma_input x Jbar=2.472 tC/ha/yr; all within the physical [0.5,8.7] envelope.)\n")
cat("2084 forecast (tC/ha):", paste(sprintf("%s %.0f", T$model, T$soc2084), collapse="  "), "\n")
