source("manuscript/figures/run_ids.R")   # auto-selects current RUN_IDs
setwd("/Users/ilmenichetti/Library/CloudStorage/OneDrive-Valtion/HIKET/SOC_modeling")
# F8b -- the trade-off / ridge face of fraction non-identifiability, for each Yasso.
#   (A) posterior correlation heatmap of the 12 transfer fractions (blocked by source
#       pool): same-pool fractions anti-correlate near -1 (data fix the NET flux out of
#       a pool, not the split); cross-pool ~0.
#   (B) the two strongest same-pool ridges as CONTINUOUS 2D DENSITY fields --
#       full bandwidth-matrix Gaussian KDE (Scott's rule: H = c * n^(-1/3) * cov, so the
#       kernel ORIENTS along the tilted ridge, unlike an axis-aligned kde2d) + level
#       curves; colour = sqrt(density) so the tails stay visible.
# Yasso20 = the main Side Arc C figure (+ table T2). Yasso07/15 = appendix companions.

# --- full bandwidth-matrix Gaussian KDE on a grid (clipped to data support) ---
kde2d_full <- function(x, y, ng = 140L, nsub = 12000L, cfac = 0.75) {
  if (length(x) > nsub) { i <- sample(length(x), nsub); x <- x[i]; y <- y[i] }
  H  <- cfac * length(x)^(-1/3) * cov(cbind(x, y))     # full (oriented) bandwidth matrix
  Hi <- solve(H); nrm <- 1 / (2*pi*sqrt(det(H)) * length(x))
  gx <- seq(min(x), max(x), length.out = ng); gy <- seq(min(y), max(y), length.out = ng)
  G  <- as.matrix(expand.grid(gx = gx, gy = gy))
  z  <- numeric(nrow(G))
  for (k in seq_along(x)) {                            # accumulate kernel over draws
    d <- cbind(G[,1] - x[k], G[,2] - y[k])
    z <- z + exp(-0.5 * rowSums((d %*% Hi) * d))
  }
  list(gx = gx, gy = gy, z = matrix(z * nrm, ng, ng))
}
# continuous density palette: white (zero) -> blue -> near-black (high density)
dpal <- colorRampPalette(c("#ffffff","#d0e1f2","#6baed6","#2171b5","#08306b","#08052e"))(256)

make_fig <- function(model, rid, outfile, do_table = FALSE) {
  p  <- readRDS(sprintf("Calibration_real_data_transient/runs/%s_posterior_%s.rds", model, rid))
  fr <- c("p_AW","p_AE","p_AN","p_WA","p_WE","p_WN","p_EA","p_EW","p_EN","p_NA","p_NW","p_NE")
  fr <- intersect(fr, colnames(p)); C <- cor(p[, fr])
  # strongest same-pool anti-correlations (for panel B + table)
  ut <- which(upper.tri(C), arr.ind = TRUE)
  tb <- data.frame(a = fr[ut[,1]], b = fr[ut[,2]], r = C[upper.tri(C)])
  tb <- tb[substr(tb$a,3,3) == substr(tb$b,3,3), ]; tb <- tb[order(tb$r), ]
  cpal <- colorRampPalette(c("#2166ac","#4393c3","#d1e5f0","white","#fddbc7","#d6604d","#b2182b"))(100)

  png(outfile, width = 12, height = 6, units = "in", res = 200)
  layout(matrix(c(1,1,2,1,1,3), nrow = 2, byrow = TRUE))
  par(mar = c(4.5,4.5,3.2,1))
  nf <- length(fr)
  image(1:nf, 1:nf, C[, nf:1], col = cpal, zlim = c(-1,1), axes = FALSE, xlab = "", ylab = "",
        main = sprintf("A . Posterior correlation of transfer fractions (%s)", model))
  axis(1, at = 1:nf, labels = fr, las = 2, tick = FALSE, cex.axis = 0.85)
  axis(2, at = 1:nf, labels = rev(fr), las = 1, tick = FALSE, cex.axis = 0.85)
  for (i in 1:nf) for (j in 1:nf) { v <- C[i, nf+1-j]
    if (abs(v) >= 0.3) text(i, j, sprintf("%.2f", v), cex = 0.6, col = if(abs(v)>0.7) "white" else "grey20") }
  abline(h = c(3.5,6.5,9.5), v = c(3.5,6.5,9.5), col = "grey55", lwd = 1.4)
  mtext("same-pool blocks (A|W|E|N); strong blue = near -1 trade-off", side = 1, line = 3.1, cex = 0.72, col = "grey35")
  # density ridge panels (top-2 same-pool anti-correlations)
  par(mar = c(4.2,4.4,2.6,1))
  for (i in 1:2) { a <- tb$a[i]; b <- tb$b[i]
    k <- kde2d_full(p[,a], p[,b])
    image(k$gx, k$gy, sqrt(k$z), col = dpal, xlab = a, ylab = b,
          main = sprintf("%s vs %s  (r = %.2f)", a, b, C[a,b]), font.main = 1, cex.main = 1.0)
    contour(k$gx, k$gy, k$z, add = TRUE, drawlabels = FALSE, col = adjustcolor("grey25",0.45), lwd = 0.5, nlevels = 8)
  }
  dev.off(); cat("wrote", outfile, "\n")

  if (do_table) {
    con <- file("manuscript/figures/T2_fraction_ridges.tex", "w")
    cat("% auto-generated by build_F8b_fraction_ridges.R\n\\begin{tabular}{cccc}\n\\hline\n",
        "Source pool & Fraction pair & Posterior $r$ & Interpretation \\\\\n\\hline\n", file = con)
    for (i in 1:min(6,nrow(tb))) cat(sprintf("%s & $p_{%s}\\!\\leftrightarrow\\! p_{%s}$ & %.2f & net-flux trade-off \\\\\n",
        substr(tb$a[i],3,3), substr(tb$a[i],3,4), substr(tb$b[i],3,4), tb$r[i]), file = con)
    cat("\\hline\n\\end{tabular}\n", file = con); close(con); cat("wrote T2_fraction_ridges.tex\n")
  }
}

make_fig("Yasso20", RID[["Yasso20"]], "manuscript/figures/F8b_fraction_ridges.png", do_table = TRUE)
make_fig("Yasso07", RID[["Yasso07"]], "manuscript/figures/F8b_fraction_ridges_Yasso07.png")  # appendix
make_fig("Yasso15", RID[["Yasso15"]], "manuscript/figures/F8b_fraction_ridges_Yasso15.png")  # appendix
